server:
  port: 8080

spring:
  application:
    name: spring-security-demo

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: PLACEHOLDER
            client-secret: PLACEHOLDER

logging:
  level:
    org.springframework.security: TRACE
